//! JSON output: a generic versioned envelope for all `RuleSteward` machine-readable output.
//!
//! # Envelope shape (issue #62, locked 2026-06-03)
//!
//! Every JSON-emitting verb produces:
//! ```json
//! { "schemaVersion": <u32>, "kind": "<payload-kind>", <payload fields...> }
//! ```
//!
//! # Tolerant-reader contract
//!
//! - `schemaVersion` is PER-KIND: each `kind` carries its own version,
//!   versioned independently.
//! - Bump trigger is BREAKING-ONLY: removing/renaming/retyping a field bumps
//!   that kind's version. Adding an optional field or a whole new `kind` is
//!   free (no bump). Consumers ignore unknown fields and dispatch on `kind`.
//!
//! # Known-kind registry
//!
//! | kind            | schemaVersion | owner module      |
//! |-----------------|---------------|-------------------|
//! | `lint`          | 1             | this module       |
//! | `trust-entries` | 1             | `output::trustdb` |
//! | `explain`       | TBD           | explain pipeline  |
//! | `auditd-cost`   | TBD           | auditd pipeline   |
//! | `selinux-triage`| TBD           | selinux pipeline  |
//!
//! Future pipelines register their kind + version constant in their OWN module
//! and call [`render_envelope`] - they do NOT edit this file.

use rulesteward_core::Diagnostic;
use serde::Serialize;

/// Schema version for the `lint` kind. Bumps only on a breaking change to the
/// lint payload (field removal, rename, or retype). Adding new optional fields
/// is free.
pub const LINT_SCHEMA_VERSION: u32 = 1;

/// Generic versioned envelope. Flattens the payload fields alongside
/// `schemaVersion` and `kind` so each kind's fields appear at the top level.
#[derive(Serialize)]
struct Envelope<'a, T: Serialize> {
    #[serde(rename = "schemaVersion")]
    schema_version: u32,
    kind: &'a str,
    #[serde(flatten)]
    payload: &'a T,
}

/// Lint payload - the fields that appear under the `lint` kind.
#[derive(Serialize)]
struct LintPayload<'a> {
    diagnostics: &'a [Diagnostic],
}

/// Render an arbitrary payload as a versioned envelope JSON string.
///
/// Produces `{ "schemaVersion": <schema_version>, "kind": "<kind>", <payload fields...> }`
/// with a trailing newline.
///
/// Future pipelines call this with their own `kind` string, version constant,
/// and payload struct - without editing this file.
#[must_use]
pub fn render_envelope<T: Serialize>(kind: &str, schema_version: u32, payload: &T) -> String {
    let envelope = Envelope {
        schema_version,
        kind,
        payload,
    };
    let mut s =
        serde_json::to_string_pretty(&envelope).expect("envelope serialization cannot fail");
    s.push('\n');
    s
}

/// Render lint diagnostics as a versioned JSON envelope.
///
/// Produces `{ "schemaVersion": 1, "kind": "lint", "diagnostics": [...] }`
/// with a trailing newline. The `kind` discriminator was added in v0.2 as an
/// additive field (tolerant-reader contract: does not bump `schemaVersion`).
#[must_use]
pub fn render(diags: &[Diagnostic]) -> String {
    render_envelope(
        "lint",
        LINT_SCHEMA_VERSION,
        &LintPayload { diagnostics: diags },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use rulesteward_core::Severity;

    fn sample_diag() -> Diagnostic {
        Diagnostic::new(
            Severity::Error,
            "fapd-E01",
            5..10,
            "unknown attribute",
            "/tmp/x.rules",
            3,
            12,
        )
    }

    // --- render_envelope generic tests ---

    #[test]
    fn render_envelope_lint_kind_round_trips_diagnostic() {
        let d = sample_diag();
        let payload = LintPayload {
            diagnostics: std::slice::from_ref(&d),
        };
        let out = render_envelope("lint", 1, &payload);
        let v: serde_json::Value = serde_json::from_str(&out).expect("re-parse envelope");
        assert_eq!(v["schemaVersion"], serde_json::json!(1));
        assert_eq!(v["kind"], serde_json::json!("lint"));
        let arr = v["diagnostics"].as_array().expect("`diagnostics` array");
        assert_eq!(arr.len(), 1);
        let parsed: Diagnostic =
            serde_json::from_value(arr[0].clone()).expect("diagnostic round-trips");
        assert_eq!(parsed, d);
    }

    #[test]
    fn render_envelope_output_ends_with_newline() {
        #[derive(Serialize)]
        struct Empty {}
        let out = render_envelope("test-kind", 1, &Empty {});
        assert!(out.ends_with('\n'), "envelope output must end with newline");
    }

    #[test]
    fn render_envelope_generic_payload_flattens_own_keys() {
        // Proves the envelope is generic: an arbitrary future-kind payload
        // (e.g. auditd-cost) flattens its own fields alongside kind/schemaVersion.
        #[derive(Serialize)]
        struct CostPayload {
            dollars_low: f64,
        }
        let out = render_envelope("auditd-cost", 1, &CostPayload { dollars_low: 0.42 });
        let v: serde_json::Value = serde_json::from_str(&out).expect("re-parse");
        assert_eq!(v["kind"], serde_json::json!("auditd-cost"));
        assert_eq!(v["schemaVersion"], serde_json::json!(1));
        assert!(
            v["dollars_low"].is_number(),
            "`dollars_low` must appear at the top level: {out}"
        );
    }

    // --- render (public lint entry point) tests - kept/adapted from v0.1 ---

    #[test]
    fn json_is_versioned_envelope_with_diagnostics_array() {
        // The public `render` must produce kind:"lint" + schemaVersion:1 + diagnostics array.
        let d = sample_diag();
        let out = render(std::slice::from_ref(&d));
        let v: serde_json::Value = serde_json::from_str(&out).expect("re-parse json output");
        assert_eq!(
            v["schemaVersion"],
            serde_json::json!(1),
            "JSON output must carry schemaVersion=1: {out}"
        );
        assert_eq!(
            v["kind"],
            serde_json::json!("lint"),
            "JSON output must carry kind=lint: {out}"
        );
        let arr = v["diagnostics"]
            .as_array()
            .expect("`diagnostics` must be an array");
        assert_eq!(arr.len(), 1);
        let parsed: Diagnostic =
            serde_json::from_value(arr[0].clone()).expect("diagnostic round-trips in envelope");
        assert_eq!(parsed, d);
    }

    #[test]
    fn json_empty_diags_is_envelope_with_empty_array_not_bare_array() {
        let out = render(&[]);
        let v: serde_json::Value = serde_json::from_str(&out).expect("re-parse");
        assert_eq!(v["schemaVersion"], serde_json::json!(1));
        assert_eq!(v["kind"], serde_json::json!("lint"));
        assert!(
            v["diagnostics"]
                .as_array()
                .expect("`diagnostics` array")
                .is_empty()
        );
        assert!(
            v.is_object(),
            "JSON is a versioned envelope object, not a bare array"
        );
    }

    #[test]
    fn json_output_ends_with_newline() {
        // Machine-readable output ends with a trailing newline (shell-pipeline safety).
        assert!(render(&[]).ends_with('\n'));
    }
}
