//! The rules file, parsed far enough to answer "what is rule N, and can anything we
//! emit resolve a denial by it?". Pure: the caller does the `fs::read`.
//!
//! Rule text is `String` and not `Vec<u8>`, against §4's byte rule, deliberately: the
//! text is never emitted, only quoted into a `Diagnostic.msg`, which is already a
//! `String`. Lines are converted with `String::from_utf8_lossy`, so a non-UTF-8 rule
//! shows replacement characters in a diagnostic and nothing else changes. Do not
//! "fix" this to bytes; there is nothing downstream that would use them.

/// One rule of the compiled set, in the daemon's own numbering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Rule {
    /// 1-based, the `rule=` a record carries.
    pub number: usize,
    /// The line as written, trimmed. Only ever quoted in a diagnostic.
    pub text: String,
    /// The first token: `allow`, `deny`, `deny_audit`, `deny_syslog`, `deny_log`.
    pub decision: String,
    /// The tokens after the decision and before the bare `:`.
    pub subject: Vec<String>,
    /// `None` when the line is ORIGINAL format, which has no object side at all and
    /// therefore can never satisfy the "object side is exactly `all`" test.
    pub object: Option<Vec<String>>,
}

/// Every line that is not blank, `#` or `%set` is a rule; that is the whole grammar
/// (`nv_split` recognises three line shapes) and the whole of `fapolicyd-cli --list`.
///
/// A skipped line consumes no rule number. fagenrules keeps a whitespace-only line in
/// `compiled.rules` -- its `length($0) < 1` tests emptiness, not blankness -- while the
/// daemon and `--list` skip it, so the counter must skip it too.
pub fn parse(file: &[u8]) -> Vec<Rule> {
    let mut rules = Vec::new();
    for line in file.split(|&b| b == b'\n') {
        let line = String::from_utf8_lossy(line);
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with('%') {
            continue;
        }
        rules.push(Rule::new(rules.len() + 1, line));
    }
    rules
}

pub fn find(rules: &[Rule], number: usize) -> Option<&Rule> {
    rules.iter().find(|r| r.number == number)
}

impl Rule {
    /// No unescaping anywhere: the rule language has no escape mechanism and no
    /// quoting, so `%set` references and `pattern=` values are stored literally.
    pub(crate) fn new(number: usize, line: &str) -> Rule {
        let line = line.trim();
        let mut tokens = line.split_whitespace().map(str::to_string);
        let decision = tokens.next().unwrap_or_default();
        let rest: Vec<String> = tokens.collect();
        let (subject, object) = match rest.iter().position(|t| t == ":") {
            Some(i) => (rest[..i].to_vec(), Some(rest[i + 1..].to_vec())),
            None => (rest, None),
        };
        Rule {
            number,
            text: line.to_string(),
            decision,
            subject,
            object,
        }
    }

    /// A rule that constrains only the process refuses: nothing scoped to a path, and
    /// no trust entry, can change the outcome.
    ///
    /// `decision.starts_with("deny")` is not redundant with the record being a denial:
    /// a denial record's `rule=N` is a deny rule by construction, so a lookup landing
    /// on an `allow` says the rules file is not this log's. An object side of exactly
    /// `all` is "the rule places no constraint on the file", and the subject clause is
    /// "names anything beyond `perm=` and `all`" -- which is what keeps the
    /// denyall-shaped `deny_audit perm=execute all : all` out.
    pub fn refuses(&self) -> bool {
        self.decision.starts_with("deny")
            && self.object.as_deref().is_some_and(|o| o == ["all"])
            && self
                .subject
                .iter()
                .any(|t| t != "all" && !t.starts_with("perm="))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The daemon's own `Loading rule file:` listing on a default Rocky 9 install,
    /// verbatim, from `rocky9-base-cli-trust-daemon.log`. It reports `Loaded 14 rules`.
    const ROCKY9: &[u8] = b"\
## This file is automatically generated from /etc/fapolicyd/rules.d
%languages=application/x-bytecode.ocaml,application/x-bytecode.python,application/java-archive,text/x-java,application/x-java-applet,application/javascript,text/javascript,text/x-awk,text/x-gawk,text/x-lisp,application/x-elc,text/x-lua,text/x-m4,text/x-nftables,text/x-perl,text/x-php,text/x-script.python,text/x-python,text/x-R,text/x-ruby,text/x-script.guile,text/x-tcl,text/x-luatex,text/x-systemtap
allow perm=any uid=0 : dir=/var/tmp/
allow perm=any uid=0 trust=1 : all
allow perm=open exe=/usr/bin/rpm : all
allow perm=open exe=/usr/bin/python3.9 comm=dnf : all
deny_audit perm=any pattern=ld_so : all
deny_audit perm=any all : ftype=application/x-bad-elf
allow perm=open all : ftype=application/x-sharedlib trust=1
deny_audit perm=open all : ftype=application/x-sharedlib
allow perm=execute all : trust=1
allow perm=open all : ftype=%languages trust=1
deny_audit perm=any all : ftype=%languages
allow perm=any all : ftype=text/x-shellscript
deny_audit perm=execute all : all
allow perm=open all : all
";

    #[test]
    fn the_rocky9_ruleset_numbers_fourteen_rules() {
        let r = parse(ROCKY9);
        assert_eq!(r.len(), 14, "the daemon logged `Loaded 14 rules`");
        assert_eq!(r[0].number, 1, "the comment and the %set consume no number");
        assert_eq!(r[0].text, "allow perm=any uid=0 : dir=/var/tmp/");
    }

    #[test]
    fn the_ld_so_deny_is_rule_five_not_six() {
        let r = parse(ROCKY9);
        assert_eq!(
            find(&r, 5).unwrap().text,
            "deny_audit perm=any pattern=ld_so : all"
        );
        assert_eq!(
            find(&r, 8).unwrap().text,
            "deny_audit perm=open all : ftype=application/x-sharedlib"
        );
        assert_eq!(
            find(&r, 13).unwrap().text,
            "deny_audit perm=execute all : all"
        );
    }

    #[test]
    fn only_the_subject_side_rule_refuses() {
        for r in parse(ROCKY9) {
            assert_eq!(r.refuses(), r.number == 5, "rule {}: {}", r.number, r.text);
        }
    }

    #[test]
    fn an_original_format_rule_never_refuses() {
        let r = Rule::new(1, "deny_audit perm=any pattern=ld_so");
        assert_eq!(r.object, None);
        assert!(
            !r.refuses(),
            "original format has no object side to be `all`"
        );
    }

    #[test]
    fn an_allow_rule_never_refuses() {
        assert!(!Rule::new(3, "allow perm=open exe=/usr/bin/rpm : all").refuses());
    }

    #[test]
    fn an_exe_only_deny_refuses() {
        assert!(Rule::new(1, "deny perm=execute exe=/usr/bin/foo : all").refuses());
    }
}
